#include "riscv_test.h"
#include "test_macros.h"

RVTEST_RV64UV

RVTEST_CODE_BEGIN

  li t0, -1

  vsetvli t1, t0, e8, m1, ta, ma
  vmsof.m v29, v4

  vmsof.m v28, v21, v0.t

  vmsof.m v23, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v28, v29

  vmsof.m v17, v27, v0.t

  vmsof.m v29, v4

  vmsof.m v22, v14, v0.t

  vmsof.m v24, v3

  vmsof.m v24, v7, v0.t

  vmsof.m v10, v16

  vmsof.m v16, v19, v0.t

  vmsof.m v4, v31

  vmsof.m v25, v7, v0.t

  vmsof.m v17, v12

  vmsof.m v13, v14, v0.t

  vmsof.m v1, v11

  vmsof.m v10, v27, v0.t

  vmsof.m v25, v11

  vmsof.m v29, v7, v0.t

  vmsof.m v13, v27

  vmsof.m v23, v27, v0.t

  vmsof.m v10, v29

  vmsof.m v8, v23, v0.t

  vmsof.m v20, v28

  vmsof.m v23, v13, v0.t

  vmsof.m v8, v29

  vmsof.m v12, v8, v0.t

  vmsof.m v29, v30

  vmsof.m v4, v1, v0.t

  vmsof.m v12, v24

  vmsof.m v29, v4, v0.t

  vmsof.m v16, v30

  vmsof.m v26, v28, v0.t

  vmsof.m v14, v4

  vmsof.m v22, v18, v0.t

  vmsof.m v14, v3

  vmsof.m v7, v1, v0.t

  vmsof.m v15, v11

  vmsof.m v17, v21, v0.t

  vmsof.m v29, v31

  vmsof.m v3, v18, v0.t

  vmsof.m v15, v3

  vmsof.m v24, v15, v0.t

  vmsof.m v6, v4

  vmsof.m v16, v24, v0.t

  vmsof.m v22, v3

  vmsof.m v25, v26, v0.t

  vmsof.m v5, v28

  vmsof.m v3, v10, v0.t

  vmsof.m v17, v6

  vmsof.m v10, v11, v0.t

  vmsof.m v1, v13

  vmsof.m v13, v6, v0.t

  vmsof.m v16, v29

  vmsof.m v15, v8, v0.t

  vmsof.m v7, v24

  vmsof.m v20, v19, v0.t

  vmsof.m v27, v30

  vmsof.m v8, v13, v0.t

  vmsof.m v28, v19

  vmsof.m v20, v9, v0.t

  vmsof.m v16, v22

  vmsof.m v24, v18, v0.t

  vmsof.m v3, v8

  vmsof.m v17, v29, v0.t

  vmsof.m v16, v21

  vmsof.m v9, v22, v0.t

  vmsof.m v30, v14

  vmsof.m v25, v2, v0.t

  vmsof.m v28, v16

  vmsof.m v12, v3, v0.t

  vmsof.m v3, v4

  vmsof.m v17, v14, v0.t

  vmsof.m v25, v9

  vmsof.m v22, v6, v0.t

  vmsof.m v27, v11

  vmsof.m v22, v10, v0.t

  vmsof.m v26, v25

  vmsof.m v1, v28, v0.t

  vmsof.m v11, v5

  vmsof.m v5, v21, v0.t

  vmsof.m v18, v4

  vmsof.m v2, v9, v0.t

  vmsof.m v6, v24

  vmsof.m v10, v24, v0.t

  vmsof.m v29, v21

  vmsof.m v19, v2, v0.t

  vmsof.m v14, v8

  vmsof.m v17, v19, v0.t

  vmsof.m v14, v6

  vmsof.m v22, v31, v0.t

  vmsof.m v19, v26

  vmsof.m v12, v28, v0.t

  vmsof.m v12, v21

  vmsof.m v26, v6, v0.t

  vmsof.m v27, v10

  vmsof.m v3, v1, v0.t

  vmsof.m v3, v22

  vmsof.m v17, v8, v0.t

  vmsof.m v31, v19

  vmsof.m v7, v19, v0.t

  vmsof.m v26, v31

  vmsof.m v13, v3, v0.t

  vmsof.m v8, v1

  vmsof.m v14, v3, v0.t

  vmsof.m v17, v13

  vmsof.m v28, v1, v0.t

  vmsof.m v28, v10

  vmsof.m v30, v14, v0.t

  vmsof.m v5, v13

  vmsof.m v17, v12, v0.t

  vmsof.m v27, v5

  vmsof.m v26, v25, v0.t

  vmsof.m v12, v15

  vmsof.m v18, v16, v0.t

  vmsof.m v31, v3

  vmsof.m v15, v19, v0.t

  vmsof.m v15, v11

  vmsof.m v24, v22, v0.t

  vmsof.m v6, v24

  vmsof.m v15, v1, v0.t

  vmsof.m v27, v26

  vmsof.m v15, v2, v0.t

  vmsof.m v20, v4

  vmsof.m v22, v15, v0.t

  vmsof.m v18, v20

  vmsof.m v18, v8, v0.t

  vmsof.m v11, v18

  vmsof.m v14, v19, v0.t

  vmsof.m v22, v20

  vmsof.m v1, v6, v0.t

  vmsof.m v18, v12

  vmsof.m v13, v14, v0.t

  vmsof.m v13, v25

  vmsof.m v27, v16, v0.t

  vmsof.m v7, v23

  vmsof.m v5, v27, v0.t

  vmsof.m v21, v30

  vmsof.m v2, v1, v0.t

  vmsof.m v4, v8

  vmsof.m v25, v16, v0.t

  vmsof.m v23, v13

  vmsof.m v7, v8, v0.t

  vmsof.m v1, v23

  vmsof.m v19, v20, v0.t

  vmsof.m v19, v8

  vmsof.m v29, v31, v0.t

  vmsof.m v1, v20

  vmsof.m v12, v20, v0.t

  vmsof.m v9, v31

  vmsof.m v5, v19, v0.t

  vmsof.m v12, v27

  vmsof.m v3, v22, v0.t

  vmsof.m v25, v21

  vmsof.m v10, v20, v0.t

  vmsof.m v28, v10

  vmsof.m v13, v30, v0.t

  vmsof.m v17, v1

  vmsof.m v28, v15, v0.t

  vmsof.m v23, v2

  vmsof.m v14, v8, v0.t

  vmsof.m v9, v23

  vmsof.m v12, v30, v0.t

  vmsof.m v6, v27

  vmsof.m v23, v30, v0.t

  vmsof.m v27, v23

  vmsof.m v5, v14, v0.t

  vmsof.m v9, v14

  vmsof.m v7, v5, v0.t

  vmsof.m v25, v26

  vmsof.m v9, v22, v0.t

  vmsof.m v4, v21

  vmsof.m v3, v23, v0.t

  vmsof.m v3, v25

  vmsof.m v27, v21, v0.t

  vmsof.m v14, v11

  vmsof.m v6, v27, v0.t

  vmsof.m v17, v22

  vmsof.m v7, v24, v0.t

  vmsof.m v21, v9

  vmsof.m v8, v17, v0.t

  vmsof.m v1, v22

  vmsof.m v7, v18, v0.t

  vmsof.m v10, v15

  vmsof.m v9, v24, v0.t

  vmsof.m v24, v7

  vmsof.m v14, v19, v0.t

  vmsof.m v4, v2

  vmsof.m v31, v8, v0.t

  vmsof.m v25, v1

  vmsof.m v18, v14, v0.t

  vmsof.m v5, v6

  vmsof.m v5, v10, v0.t

  vmsof.m v22, v9

  vmsof.m v20, v8, v0.t

  vmsof.m v5, v27

  vmsof.m v18, v22, v0.t

  vmsof.m v7, v24

  vmsof.m v26, v18, v0.t

  vsetvli t1, t0, e8, m2, ta, ma
  vmsof.m v18, v2

  vmsof.m v18, v16, v0.t

  vmsof.m v10, v6

  vmsof.m v12, v20, v0.t

  vmsof.m v10, v30

  vmsof.m v10, v14, v0.t

  vmsof.m v28, v12

  vmsof.m v30, v10, v0.t

  vmsof.m v24, v26

  vmsof.m v12, v18, v0.t

  vmsof.m v14, v10

  vmsof.m v14, v22, v0.t

  vmsof.m v8, v6

  vmsof.m v14, v30, v0.t

  vmsof.m v24, v2

  vmsof.m v18, v16, v0.t

  vmsof.m v24, v2

  vmsof.m v26, v12, v0.t

  vmsof.m v2, v20

  vmsof.m v28, v10, v0.t

  vmsof.m v28, v18

  vmsof.m v26, v24, v0.t

  vmsof.m v22, v26

  vmsof.m v12, v24, v0.t

  vmsof.m v10, v30

  vmsof.m v16, v8, v0.t

  vmsof.m v4, v22

  vmsof.m v12, v22, v0.t

  vmsof.m v12, v4

  vmsof.m v14, v22, v0.t

  vmsof.m v20, v22

  vmsof.m v12, v8, v0.t

  vmsof.m v28, v14

  vmsof.m v28, v4, v0.t

  vmsof.m v22, v6

  vmsof.m v30, v14, v0.t

  vmsof.m v2, v10

  vmsof.m v20, v4, v0.t

  vmsof.m v16, v14

  vmsof.m v16, v2, v0.t

  vmsof.m v18, v12

  vmsof.m v10, v26, v0.t

  vmsof.m v16, v8

  vmsof.m v10, v30, v0.t

  vmsof.m v10, v4

  vmsof.m v2, v14, v0.t

  vmsof.m v26, v22

  vmsof.m v30, v18, v0.t

  vmsof.m v8, v26

  vmsof.m v8, v30, v0.t

  vmsof.m v26, v16

  vmsof.m v6, v2, v0.t

  vmsof.m v30, v8

  vmsof.m v6, v14, v0.t

  vmsof.m v26, v12

  vmsof.m v24, v26, v0.t

  vmsof.m v10, v4

  vmsof.m v10, v14, v0.t

  vmsof.m v14, v20

  vmsof.m v6, v24, v0.t

  vmsof.m v22, v8

  vmsof.m v28, v24, v0.t

  vmsof.m v16, v20

  vmsof.m v10, v16, v0.t

  vmsof.m v20, v10

  vmsof.m v6, v10, v0.t

  vmsof.m v4, v6

  vmsof.m v20, v8, v0.t

  vmsof.m v2, v10

  vmsof.m v24, v16, v0.t

  vmsof.m v14, v18

  vmsof.m v10, v26, v0.t

  vmsof.m v2, v24

  vmsof.m v26, v18, v0.t

  vmsof.m v8, v20

  vmsof.m v12, v18, v0.t

  vmsof.m v30, v18

  vmsof.m v24, v28, v0.t

  vmsof.m v4, v20

  vmsof.m v26, v20, v0.t

  vmsof.m v10, v22

  vmsof.m v8, v10, v0.t

  vmsof.m v16, v28

  vmsof.m v26, v28, v0.t

  vmsof.m v30, v28

  vmsof.m v14, v10, v0.t

  vmsof.m v4, v6

  vmsof.m v18, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v14, v12, v0.t

  vmsof.m v24, v2

  vmsof.m v4, v24, v0.t

  vmsof.m v22, v12

  vmsof.m v18, v6, v0.t

  vmsof.m v12, v26

  vmsof.m v8, v26, v0.t

  vmsof.m v26, v8

  vmsof.m v10, v2, v0.t

  vmsof.m v20, v18

  vmsof.m v22, v24, v0.t

  vmsof.m v12, v4

  vmsof.m v12, v2, v0.t

  vmsof.m v16, v12

  vmsof.m v16, v22, v0.t

  vmsof.m v26, v24

  vmsof.m v18, v20, v0.t

  vmsof.m v18, v4

  vmsof.m v16, v6, v0.t

  vmsof.m v16, v12

  vmsof.m v6, v18, v0.t

  vmsof.m v14, v20

  vmsof.m v18, v8, v0.t

  vmsof.m v4, v30

  vmsof.m v2, v30, v0.t

  vmsof.m v24, v20

  vmsof.m v24, v30, v0.t

  vmsof.m v6, v14

  vmsof.m v16, v30, v0.t

  vmsof.m v16, v10

  vmsof.m v30, v6, v0.t

  vmsof.m v10, v20

  vmsof.m v24, v22, v0.t

  vmsof.m v16, v24

  vmsof.m v20, v18, v0.t

  vmsof.m v24, v6

  vmsof.m v22, v28, v0.t

  vmsof.m v16, v12

  vmsof.m v18, v26, v0.t

  vmsof.m v16, v12

  vmsof.m v2, v22, v0.t

  vmsof.m v18, v16

  vmsof.m v2, v26, v0.t

  vmsof.m v6, v4

  vmsof.m v20, v26, v0.t

  vmsof.m v16, v26

  vmsof.m v30, v10, v0.t

  vmsof.m v12, v2

  vmsof.m v10, v14, v0.t

  vmsof.m v28, v30

  vmsof.m v28, v14, v0.t

  vmsof.m v12, v24

  vmsof.m v16, v4, v0.t

  vmsof.m v8, v2

  vmsof.m v14, v28, v0.t

  vmsof.m v22, v20

  vmsof.m v14, v30, v0.t

  vmsof.m v2, v28

  vmsof.m v30, v4, v0.t

  vmsof.m v16, v14

  vmsof.m v14, v24, v0.t

  vmsof.m v28, v14

  vmsof.m v10, v12, v0.t

  vmsof.m v22, v18

  vmsof.m v14, v4, v0.t

  vmsof.m v4, v8

  vmsof.m v4, v6, v0.t

  vmsof.m v4, v22

  vmsof.m v10, v24, v0.t

  vmsof.m v24, v14

  vmsof.m v6, v4, v0.t

  vmsof.m v28, v12

  vmsof.m v16, v30, v0.t

  vmsof.m v24, v10

  vmsof.m v30, v16, v0.t

  vmsof.m v14, v30

  vmsof.m v20, v16, v0.t

  vmsof.m v12, v30

  vmsof.m v4, v16, v0.t

  vmsof.m v16, v30

  vmsof.m v2, v28, v0.t

  vmsof.m v18, v6

  vmsof.m v16, v12, v0.t

  vmsof.m v20, v4

  vmsof.m v14, v2, v0.t

  vmsof.m v24, v6

  vmsof.m v2, v4, v0.t

  vmsof.m v26, v10

  vmsof.m v20, v26, v0.t

  vmsof.m v10, v28

  vmsof.m v12, v14, v0.t

  vmsof.m v24, v12

  vmsof.m v14, v18, v0.t

  vmsof.m v6, v30

  vmsof.m v12, v10, v0.t

  vmsof.m v24, v26

  vmsof.m v8, v4, v0.t

  vmsof.m v30, v26

  vmsof.m v8, v2, v0.t

  vmsof.m v24, v26

  vmsof.m v16, v24, v0.t

  vmsof.m v22, v16

  vmsof.m v16, v4, v0.t

  vmsof.m v14, v30

  vmsof.m v18, v22, v0.t

  vmsof.m v16, v12

  vmsof.m v2, v16, v0.t

  vmsof.m v4, v24

  vmsof.m v30, v20, v0.t

  vmsof.m v6, v28

  vmsof.m v16, v6, v0.t

  vsetvli t1, t0, e8, m4, ta, ma
  vmsof.m v4, v12

  vmsof.m v24, v8, v0.t

  vmsof.m v20, v16

  vmsof.m v28, v8, v0.t

  vmsof.m v28, v4

  vmsof.m v24, v4, v0.t

  vmsof.m v24, v4

  vmsof.m v4, v8, v0.t

  vmsof.m v16, v20

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v20

  vmsof.m v28, v24, v0.t

  vmsof.m v8, v28

  vmsof.m v20, v4, v0.t

  vmsof.m v12, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v28, v0.t

  vmsof.m v4, v16

  vmsof.m v4, v28, v0.t

  vmsof.m v16, v8

  vmsof.m v28, v24, v0.t

  vmsof.m v24, v20

  vmsof.m v20, v28, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v4, v0.t

  vmsof.m v24, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v28, v12

  vmsof.m v8, v16, v0.t

  vmsof.m v28, v4

  vmsof.m v16, v12, v0.t

  vmsof.m v4, v12

  vmsof.m v12, v8, v0.t

  vmsof.m v28, v16

  vmsof.m v12, v4, v0.t

  vmsof.m v4, v28

  vmsof.m v20, v28, v0.t

  vmsof.m v20, v12

  vmsof.m v12, v4, v0.t

  vmsof.m v4, v28

  vmsof.m v28, v20, v0.t

  vmsof.m v12, v16

  vmsof.m v12, v16, v0.t

  vmsof.m v28, v16

  vmsof.m v16, v4, v0.t

  vmsof.m v8, v28

  vmsof.m v16, v24, v0.t

  vmsof.m v12, v20

  vmsof.m v28, v4, v0.t

  vmsof.m v8, v12

  vmsof.m v4, v24, v0.t

  vmsof.m v4, v16

  vmsof.m v16, v20, v0.t

  vmsof.m v20, v8

  vmsof.m v28, v4, v0.t

  vmsof.m v28, v20

  vmsof.m v12, v8, v0.t

  vmsof.m v4, v20

  vmsof.m v12, v8, v0.t

  vmsof.m v28, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v28, v20

  vmsof.m v4, v24, v0.t

  vmsof.m v28, v20

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v12

  vmsof.m v4, v12, v0.t

  vmsof.m v28, v24

  vmsof.m v12, v16, v0.t

  vmsof.m v4, v24

  vmsof.m v12, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v28, v24, v0.t

  vmsof.m v20, v28

  vmsof.m v24, v4, v0.t

  vmsof.m v28, v4

  vmsof.m v24, v20, v0.t

  vmsof.m v8, v4

  vmsof.m v12, v20, v0.t

  vmsof.m v28, v16

  vmsof.m v4, v16, v0.t

  vmsof.m v24, v12

  vmsof.m v4, v12, v0.t

  vmsof.m v24, v4

  vmsof.m v28, v12, v0.t

  vmsof.m v4, v12

  vmsof.m v24, v28, v0.t

  vmsof.m v28, v4

  vmsof.m v24, v8, v0.t

  vmsof.m v20, v28

  vmsof.m v28, v8, v0.t

  vmsof.m v4, v24

  vmsof.m v28, v8, v0.t

  vmsof.m v20, v28

  vmsof.m v16, v4, v0.t

  vmsof.m v4, v8

  vmsof.m v28, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v12

  vmsof.m v8, v16, v0.t

  vmsof.m v4, v12

  vmsof.m v24, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v20, v16, v0.t

  vmsof.m v8, v12

  vmsof.m v12, v24, v0.t

  vmsof.m v12, v24

  vmsof.m v20, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v12, v8, v0.t

  vmsof.m v12, v28

  vmsof.m v20, v24, v0.t

  vmsof.m v28, v4

  vmsof.m v20, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v20, v4, v0.t

  vmsof.m v16, v4

  vmsof.m v4, v12, v0.t

  vmsof.m v16, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v12, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v12

  vmsof.m v20, v28, v0.t

  vmsof.m v8, v12

  vmsof.m v4, v8, v0.t

  vmsof.m v28, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v28

  vmsof.m v20, v16, v0.t

  vmsof.m v24, v20

  vmsof.m v8, v12, v0.t

  vmsof.m v8, v24

  vmsof.m v12, v24, v0.t

  vmsof.m v28, v20

  vmsof.m v28, v4, v0.t

  vmsof.m v8, v20

  vmsof.m v12, v4, v0.t

  vmsof.m v12, v28

  vmsof.m v24, v16, v0.t

  vmsof.m v20, v24

  vmsof.m v20, v24, v0.t

  vmsof.m v12, v24

  vmsof.m v20, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v12, v16, v0.t

  vmsof.m v4, v12

  vmsof.m v12, v16, v0.t

  vmsof.m v8, v12

  vmsof.m v20, v8, v0.t

  vmsof.m v20, v28

  vmsof.m v4, v24, v0.t

  vmsof.m v12, v16

  vmsof.m v20, v24, v0.t

  vmsof.m v28, v12

  vmsof.m v12, v8, v0.t

  vmsof.m v20, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v28, v0.t

  vmsof.m v28, v12

  vmsof.m v24, v8, v0.t

  vmsof.m v4, v20

  vmsof.m v4, v20, v0.t

  vmsof.m v4, v28

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v12

  vmsof.m v20, v8, v0.t

  vmsof.m v4, v8

  vmsof.m v16, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v20, v8, v0.t

  vmsof.m v24, v20

  vmsof.m v4, v20, v0.t

  vmsof.m v16, v24

  vmsof.m v20, v8, v0.t

  vmsof.m v8, v28

  vmsof.m v4, v12, v0.t

  vmsof.m v12, v28

  vmsof.m v20, v16, v0.t

  vmsof.m v16, v4

  vmsof.m v8, v20, v0.t

  vmsof.m v4, v20

  vmsof.m v8, v28, v0.t

  vmsof.m v20, v28

  vmsof.m v4, v16, v0.t

  vmsof.m v16, v4

  vmsof.m v8, v24, v0.t

  vmsof.m v20, v16

  vmsof.m v8, v12, v0.t

  vmsof.m v28, v16

  vmsof.m v8, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v20, v16, v0.t

  vmsof.m v12, v8

  vmsof.m v16, v4, v0.t

  vsetvli t1, t0, e8, m8, ta, ma
  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vsetvli t1, t0, e16, m1, ta, ma
  vmsof.m v14, v1

  vmsof.m v15, v7, v0.t

  vmsof.m v4, v26

  vmsof.m v5, v16, v0.t

  vmsof.m v5, v27

  vmsof.m v25, v4, v0.t

  vmsof.m v19, v26

  vmsof.m v2, v6, v0.t

  vmsof.m v9, v17

  vmsof.m v20, v2, v0.t

  vmsof.m v23, v24

  vmsof.m v26, v28, v0.t

  vmsof.m v6, v30

  vmsof.m v8, v7, v0.t

  vmsof.m v7, v14

  vmsof.m v2, v16, v0.t

  vmsof.m v14, v31

  vmsof.m v16, v20, v0.t

  vmsof.m v31, v13

  vmsof.m v6, v10, v0.t

  vmsof.m v15, v24

  vmsof.m v14, v3, v0.t

  vmsof.m v5, v12

  vmsof.m v5, v21, v0.t

  vmsof.m v3, v4

  vmsof.m v6, v24, v0.t

  vmsof.m v16, v14

  vmsof.m v1, v16, v0.t

  vmsof.m v5, v30

  vmsof.m v26, v23, v0.t

  vmsof.m v21, v10

  vmsof.m v5, v10, v0.t

  vmsof.m v3, v19

  vmsof.m v7, v13, v0.t

  vmsof.m v10, v1

  vmsof.m v19, v2, v0.t

  vmsof.m v11, v14

  vmsof.m v16, v25, v0.t

  vmsof.m v16, v23

  vmsof.m v5, v4, v0.t

  vmsof.m v28, v11

  vmsof.m v13, v6, v0.t

  vmsof.m v5, v27

  vmsof.m v15, v18, v0.t

  vmsof.m v20, v28

  vmsof.m v24, v26, v0.t

  vmsof.m v18, v29

  vmsof.m v11, v5, v0.t

  vmsof.m v12, v2

  vmsof.m v18, v15, v0.t

  vmsof.m v22, v11

  vmsof.m v23, v17, v0.t

  vmsof.m v12, v21

  vmsof.m v7, v14, v0.t

  vmsof.m v25, v28

  vmsof.m v26, v28, v0.t

  vmsof.m v1, v2

  vmsof.m v27, v22, v0.t

  vmsof.m v27, v30

  vmsof.m v18, v5, v0.t

  vmsof.m v2, v4

  vmsof.m v18, v1, v0.t

  vmsof.m v27, v28

  vmsof.m v17, v4, v0.t

  vmsof.m v18, v12

  vmsof.m v4, v11, v0.t

  vmsof.m v23, v28

  vmsof.m v1, v18, v0.t

  vmsof.m v1, v15

  vmsof.m v9, v5, v0.t

  vmsof.m v6, v26

  vmsof.m v13, v23, v0.t

  vmsof.m v24, v8

  vmsof.m v12, v16, v0.t

  vmsof.m v28, v2

  vmsof.m v10, v31, v0.t

  vmsof.m v31, v27

  vmsof.m v18, v24, v0.t

  vmsof.m v27, v31

  vmsof.m v30, v4, v0.t

  vmsof.m v28, v7

  vmsof.m v12, v26, v0.t

  vmsof.m v11, v15

  vmsof.m v30, v4, v0.t

  vmsof.m v31, v24

  vmsof.m v2, v22, v0.t

  vmsof.m v4, v17

  vmsof.m v8, v30, v0.t

  vmsof.m v20, v2

  vmsof.m v25, v14, v0.t

  vmsof.m v17, v22

  vmsof.m v14, v11, v0.t

  vmsof.m v2, v7

  vmsof.m v13, v15, v0.t

  vmsof.m v23, v8

  vmsof.m v14, v27, v0.t

  vmsof.m v2, v30

  vmsof.m v15, v5, v0.t

  vmsof.m v17, v16

  vmsof.m v6, v9, v0.t

  vmsof.m v15, v16

  vmsof.m v12, v9, v0.t

  vmsof.m v3, v31

  vmsof.m v17, v1, v0.t

  vmsof.m v11, v16

  vmsof.m v18, v30, v0.t

  vmsof.m v10, v12

  vmsof.m v21, v31, v0.t

  vmsof.m v22, v31

  vmsof.m v24, v15, v0.t

  vmsof.m v21, v13

  vmsof.m v4, v23, v0.t

  vmsof.m v13, v30

  vmsof.m v30, v25, v0.t

  vmsof.m v23, v17

  vmsof.m v13, v29, v0.t

  vmsof.m v19, v2

  vmsof.m v6, v30, v0.t

  vmsof.m v15, v3

  vmsof.m v11, v15, v0.t

  vmsof.m v31, v9

  vmsof.m v16, v15, v0.t

  vmsof.m v28, v17

  vmsof.m v30, v19, v0.t

  vmsof.m v4, v15

  vmsof.m v6, v31, v0.t

  vmsof.m v18, v3

  vmsof.m v22, v18, v0.t

  vmsof.m v2, v9

  vmsof.m v16, v5, v0.t

  vmsof.m v23, v8

  vmsof.m v30, v13, v0.t

  vmsof.m v15, v5

  vmsof.m v11, v29, v0.t

  vmsof.m v7, v10

  vmsof.m v4, v22, v0.t

  vmsof.m v7, v22

  vmsof.m v13, v6, v0.t

  vmsof.m v7, v26

  vmsof.m v1, v28, v0.t

  vmsof.m v11, v30

  vmsof.m v11, v7, v0.t

  vmsof.m v24, v17

  vmsof.m v18, v27, v0.t

  vmsof.m v20, v23

  vmsof.m v22, v12, v0.t

  vmsof.m v5, v6

  vmsof.m v9, v19, v0.t

  vmsof.m v27, v18

  vmsof.m v29, v22, v0.t

  vmsof.m v18, v24

  vmsof.m v23, v31, v0.t

  vmsof.m v1, v25

  vmsof.m v26, v24, v0.t

  vmsof.m v21, v17

  vmsof.m v21, v13, v0.t

  vmsof.m v5, v31

  vmsof.m v2, v31, v0.t

  vmsof.m v1, v6

  vmsof.m v1, v9, v0.t

  vmsof.m v29, v19

  vmsof.m v28, v12, v0.t

  vmsof.m v4, v22

  vmsof.m v25, v30, v0.t

  vmsof.m v21, v23

  vmsof.m v12, v19, v0.t

  vmsof.m v9, v7

  vmsof.m v6, v19, v0.t

  vmsof.m v7, v14

  vmsof.m v9, v28, v0.t

  vmsof.m v15, v30

  vmsof.m v8, v27, v0.t

  vmsof.m v30, v19

  vmsof.m v17, v16, v0.t

  vmsof.m v31, v25

  vmsof.m v6, v15, v0.t

  vmsof.m v29, v28

  vmsof.m v7, v24, v0.t

  vmsof.m v3, v18

  vmsof.m v22, v5, v0.t

  vmsof.m v2, v24

  vmsof.m v18, v4, v0.t

  vmsof.m v28, v25

  vmsof.m v1, v25, v0.t

  vmsof.m v7, v27

  vmsof.m v3, v4, v0.t

  vmsof.m v10, v8

  vmsof.m v13, v27, v0.t

  vmsof.m v14, v31

  vmsof.m v10, v26, v0.t

  vmsof.m v25, v11

  vmsof.m v9, v19, v0.t

  vmsof.m v13, v5

  vmsof.m v23, v19, v0.t

  vmsof.m v26, v31

  vmsof.m v6, v16, v0.t

  vmsof.m v15, v8

  vmsof.m v17, v13, v0.t

  vmsof.m v30, v10

  vmsof.m v9, v1, v0.t

  vsetvli t1, t0, e16, m2, ta, ma
  vmsof.m v28, v10

  vmsof.m v30, v16, v0.t

  vmsof.m v30, v26

  vmsof.m v14, v4, v0.t

  vmsof.m v2, v4

  vmsof.m v18, v2, v0.t

  vmsof.m v24, v26

  vmsof.m v14, v8, v0.t

  vmsof.m v4, v26

  vmsof.m v2, v8, v0.t

  vmsof.m v18, v24

  vmsof.m v16, v14, v0.t

  vmsof.m v20, v28

  vmsof.m v24, v8, v0.t

  vmsof.m v4, v8

  vmsof.m v20, v4, v0.t

  vmsof.m v4, v28

  vmsof.m v26, v20, v0.t

  vmsof.m v26, v12

  vmsof.m v20, v18, v0.t

  vmsof.m v14, v4

  vmsof.m v22, v2, v0.t

  vmsof.m v14, v4

  vmsof.m v10, v14, v0.t

  vmsof.m v18, v14

  vmsof.m v26, v30, v0.t

  vmsof.m v6, v22

  vmsof.m v30, v6, v0.t

  vmsof.m v16, v26

  vmsof.m v8, v18, v0.t

  vmsof.m v28, v18

  vmsof.m v30, v6, v0.t

  vmsof.m v14, v4

  vmsof.m v26, v30, v0.t

  vmsof.m v4, v6

  vmsof.m v14, v20, v0.t

  vmsof.m v6, v14

  vmsof.m v14, v22, v0.t

  vmsof.m v24, v18

  vmsof.m v18, v12, v0.t

  vmsof.m v14, v30

  vmsof.m v6, v26, v0.t

  vmsof.m v30, v12

  vmsof.m v30, v26, v0.t

  vmsof.m v2, v4

  vmsof.m v8, v16, v0.t

  vmsof.m v12, v2

  vmsof.m v8, v28, v0.t

  vmsof.m v26, v2

  vmsof.m v4, v26, v0.t

  vmsof.m v24, v12

  vmsof.m v12, v2, v0.t

  vmsof.m v26, v16

  vmsof.m v20, v14, v0.t

  vmsof.m v4, v14

  vmsof.m v24, v18, v0.t

  vmsof.m v30, v14

  vmsof.m v8, v12, v0.t

  vmsof.m v6, v14

  vmsof.m v14, v16, v0.t

  vmsof.m v4, v24

  vmsof.m v12, v24, v0.t

  vmsof.m v26, v12

  vmsof.m v30, v20, v0.t

  vmsof.m v10, v30

  vmsof.m v28, v26, v0.t

  vmsof.m v16, v4

  vmsof.m v4, v6, v0.t

  vmsof.m v12, v16

  vmsof.m v10, v2, v0.t

  vmsof.m v14, v28

  vmsof.m v20, v18, v0.t

  vmsof.m v14, v24

  vmsof.m v2, v16, v0.t

  vmsof.m v18, v28

  vmsof.m v28, v30, v0.t

  vmsof.m v16, v22

  vmsof.m v4, v30, v0.t

  vmsof.m v30, v16

  vmsof.m v16, v30, v0.t

  vmsof.m v18, v10

  vmsof.m v2, v20, v0.t

  vmsof.m v16, v26

  vmsof.m v2, v30, v0.t

  vmsof.m v28, v16

  vmsof.m v6, v12, v0.t

  vmsof.m v22, v10

  vmsof.m v22, v26, v0.t

  vmsof.m v12, v18

  vmsof.m v6, v16, v0.t

  vmsof.m v6, v10

  vmsof.m v8, v26, v0.t

  vmsof.m v10, v30

  vmsof.m v18, v20, v0.t

  vmsof.m v26, v6

  vmsof.m v28, v12, v0.t

  vmsof.m v10, v16

  vmsof.m v20, v8, v0.t

  vmsof.m v12, v26

  vmsof.m v8, v18, v0.t

  vmsof.m v12, v18

  vmsof.m v18, v8, v0.t

  vmsof.m v6, v24

  vmsof.m v2, v28, v0.t

  vmsof.m v28, v6

  vmsof.m v4, v18, v0.t

  vmsof.m v8, v22

  vmsof.m v8, v16, v0.t

  vmsof.m v10, v4

  vmsof.m v6, v14, v0.t

  vmsof.m v18, v8

  vmsof.m v10, v30, v0.t

  vmsof.m v10, v16

  vmsof.m v4, v28, v0.t

  vmsof.m v30, v20

  vmsof.m v4, v6, v0.t

  vmsof.m v12, v16

  vmsof.m v30, v14, v0.t

  vmsof.m v8, v6

  vmsof.m v22, v12, v0.t

  vmsof.m v24, v2

  vmsof.m v6, v30, v0.t

  vmsof.m v12, v14

  vmsof.m v16, v22, v0.t

  vmsof.m v26, v4

  vmsof.m v28, v24, v0.t

  vmsof.m v14, v18

  vmsof.m v22, v4, v0.t

  vmsof.m v18, v22

  vmsof.m v12, v20, v0.t

  vmsof.m v12, v30

  vmsof.m v8, v4, v0.t

  vmsof.m v22, v20

  vmsof.m v26, v8, v0.t

  vmsof.m v14, v20

  vmsof.m v6, v18, v0.t

  vmsof.m v30, v16

  vmsof.m v28, v30, v0.t

  vmsof.m v14, v30

  vmsof.m v8, v4, v0.t

  vmsof.m v8, v22

  vmsof.m v10, v18, v0.t

  vmsof.m v22, v20

  vmsof.m v8, v28, v0.t

  vmsof.m v18, v22

  vmsof.m v12, v14, v0.t

  vmsof.m v4, v18

  vmsof.m v6, v24, v0.t

  vmsof.m v18, v6

  vmsof.m v24, v20, v0.t

  vmsof.m v14, v2

  vmsof.m v8, v30, v0.t

  vmsof.m v2, v24

  vmsof.m v10, v18, v0.t

  vmsof.m v24, v12

  vmsof.m v2, v24, v0.t

  vmsof.m v10, v16

  vmsof.m v2, v12, v0.t

  vmsof.m v6, v14

  vmsof.m v16, v10, v0.t

  vmsof.m v18, v2

  vmsof.m v22, v10, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v12, v0.t

  vmsof.m v8, v18

  vmsof.m v20, v6, v0.t

  vmsof.m v2, v22

  vmsof.m v30, v16, v0.t

  vmsof.m v20, v24

  vmsof.m v24, v6, v0.t

  vmsof.m v14, v4

  vmsof.m v30, v18, v0.t

  vmsof.m v6, v18

  vmsof.m v16, v30, v0.t

  vmsof.m v26, v10

  vmsof.m v16, v28, v0.t

  vmsof.m v10, v16

  vmsof.m v18, v2, v0.t

  vmsof.m v24, v12

  vmsof.m v20, v14, v0.t

  vmsof.m v30, v14

  vmsof.m v22, v28, v0.t

  vmsof.m v20, v4

  vmsof.m v22, v6, v0.t

  vmsof.m v2, v28

  vmsof.m v8, v6, v0.t

  vmsof.m v26, v18

  vmsof.m v8, v22, v0.t

  vmsof.m v28, v10

  vmsof.m v14, v10, v0.t

  vmsof.m v4, v24

  vmsof.m v12, v30, v0.t

  vmsof.m v2, v26

  vmsof.m v30, v16, v0.t

  vmsof.m v22, v16

  vmsof.m v16, v18, v0.t

  vmsof.m v18, v16

  vmsof.m v10, v16, v0.t

  vmsof.m v24, v14

  vmsof.m v2, v14, v0.t

  vsetvli t1, t0, e16, m4, ta, ma
  vmsof.m v4, v8

  vmsof.m v4, v20, v0.t

  vmsof.m v20, v28

  vmsof.m v12, v8, v0.t

  vmsof.m v4, v28

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v20

  vmsof.m v20, v28, v0.t

  vmsof.m v28, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v12, v0.t

  vmsof.m v24, v20

  vmsof.m v24, v20, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v28

  vmsof.m v12, v28, v0.t

  vmsof.m v8, v12

  vmsof.m v4, v20, v0.t

  vmsof.m v28, v24

  vmsof.m v4, v28, v0.t

  vmsof.m v16, v28

  vmsof.m v16, v12, v0.t

  vmsof.m v24, v4

  vmsof.m v12, v16, v0.t

  vmsof.m v16, v20

  vmsof.m v12, v28, v0.t

  vmsof.m v20, v28

  vmsof.m v12, v4, v0.t

  vmsof.m v20, v8

  vmsof.m v24, v28, v0.t

  vmsof.m v12, v8

  vmsof.m v20, v8, v0.t

  vmsof.m v20, v4

  vmsof.m v28, v8, v0.t

  vmsof.m v4, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v16, v28

  vmsof.m v4, v28, v0.t

  vmsof.m v8, v16

  vmsof.m v20, v4, v0.t

  vmsof.m v12, v20

  vmsof.m v16, v28, v0.t

  vmsof.m v20, v8

  vmsof.m v20, v24, v0.t

  vmsof.m v12, v4

  vmsof.m v20, v24, v0.t

  vmsof.m v4, v16

  vmsof.m v20, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v4, v16

  vmsof.m v4, v20, v0.t

  vmsof.m v20, v12

  vmsof.m v4, v8, v0.t

  vmsof.m v4, v28

  vmsof.m v28, v24, v0.t

  vmsof.m v12, v20

  vmsof.m v8, v28, v0.t

  vmsof.m v16, v12

  vmsof.m v4, v8, v0.t

  vmsof.m v4, v12

  vmsof.m v16, v12, v0.t

  vmsof.m v8, v28

  vmsof.m v20, v12, v0.t

  vmsof.m v20, v28

  vmsof.m v28, v8, v0.t

  vmsof.m v20, v4

  vmsof.m v20, v12, v0.t

  vmsof.m v12, v24

  vmsof.m v20, v16, v0.t

  vmsof.m v12, v28

  vmsof.m v8, v12, v0.t

  vmsof.m v28, v16

  vmsof.m v28, v8, v0.t

  vmsof.m v28, v8

  vmsof.m v28, v20, v0.t

  vmsof.m v12, v4

  vmsof.m v16, v24, v0.t

  vmsof.m v12, v28

  vmsof.m v16, v4, v0.t

  vmsof.m v8, v12

  vmsof.m v20, v24, v0.t

  vmsof.m v8, v20

  vmsof.m v12, v8, v0.t

  vmsof.m v12, v4

  vmsof.m v4, v20, v0.t

  vmsof.m v4, v24

  vmsof.m v20, v4, v0.t

  vmsof.m v28, v12

  vmsof.m v12, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v20, v0.t

  vmsof.m v20, v4

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v4

  vmsof.m v4, v28, v0.t

  vmsof.m v12, v4

  vmsof.m v4, v8, v0.t

  vmsof.m v28, v20

  vmsof.m v12, v16, v0.t

  vmsof.m v28, v4

  vmsof.m v28, v12, v0.t

  vmsof.m v16, v20

  vmsof.m v16, v12, v0.t

  vmsof.m v12, v4

  vmsof.m v20, v28, v0.t

  vmsof.m v16, v20

  vmsof.m v8, v4, v0.t

  vmsof.m v8, v12

  vmsof.m v28, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v4

  vmsof.m v20, v16, v0.t

  vmsof.m v4, v12

  vmsof.m v16, v12, v0.t

  vmsof.m v28, v12

  vmsof.m v4, v12, v0.t

  vmsof.m v24, v20

  vmsof.m v28, v12, v0.t

  vmsof.m v20, v28

  vmsof.m v12, v24, v0.t

  vmsof.m v20, v12

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v12, v20

  vmsof.m v24, v4, v0.t

  vmsof.m v12, v20

  vmsof.m v4, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v20, v0.t

  vmsof.m v12, v8

  vmsof.m v8, v28, v0.t

  vmsof.m v28, v20

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v12

  vmsof.m v20, v24, v0.t

  vmsof.m v28, v4

  vmsof.m v24, v16, v0.t

  vmsof.m v20, v24

  vmsof.m v20, v24, v0.t

  vmsof.m v4, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v20, v24

  vmsof.m v8, v20, v0.t

  vmsof.m v16, v28

  vmsof.m v20, v8, v0.t

  vmsof.m v8, v20

  vmsof.m v28, v8, v0.t

  vmsof.m v20, v12

  vmsof.m v20, v8, v0.t

  vmsof.m v20, v12

  vmsof.m v28, v4, v0.t

  vmsof.m v28, v16

  vmsof.m v8, v12, v0.t

  vmsof.m v24, v8

  vmsof.m v28, v24, v0.t

  vmsof.m v12, v20

  vmsof.m v16, v20, v0.t

  vmsof.m v20, v8

  vmsof.m v12, v20, v0.t

  vmsof.m v16, v12

  vmsof.m v24, v20, v0.t

  vmsof.m v16, v28

  vmsof.m v4, v8, v0.t

  vmsof.m v20, v16

  vmsof.m v20, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v20, v12, v0.t

  vmsof.m v12, v24

  vmsof.m v8, v4, v0.t

  vmsof.m v8, v20

  vmsof.m v28, v16, v0.t

  vmsof.m v24, v4

  vmsof.m v16, v4, v0.t

  vmsof.m v4, v8

  vmsof.m v20, v12, v0.t

  vmsof.m v4, v16

  vmsof.m v28, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v8, v4

  vmsof.m v12, v8, v0.t

  vmsof.m v4, v24

  vmsof.m v24, v12, v0.t

  vmsof.m v20, v12

  vmsof.m v24, v28, v0.t

  vmsof.m v16, v24

  vmsof.m v4, v16, v0.t

  vmsof.m v4, v16

  vmsof.m v20, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v20, v16, v0.t

  vmsof.m v8, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v24, v28

  vmsof.m v20, v16, v0.t

  vsetvli t1, t0, e16, m8, ta, ma
  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vsetvli t1, t0, e32, m1, ta, ma
  vmsof.m v15, v16

  vmsof.m v23, v2, v0.t

  vmsof.m v24, v21

  vmsof.m v8, v12, v0.t

  vmsof.m v27, v2

  vmsof.m v11, v21, v0.t

  vmsof.m v1, v17

  vmsof.m v20, v9, v0.t

  vmsof.m v4, v29

  vmsof.m v24, v20, v0.t

  vmsof.m v13, v15

  vmsof.m v2, v15, v0.t

  vmsof.m v29, v3

  vmsof.m v7, v1, v0.t

  vmsof.m v2, v25

  vmsof.m v13, v25, v0.t

  vmsof.m v3, v15

  vmsof.m v28, v30, v0.t

  vmsof.m v5, v14

  vmsof.m v23, v2, v0.t

  vmsof.m v27, v23

  vmsof.m v17, v16, v0.t

  vmsof.m v11, v20

  vmsof.m v21, v7, v0.t

  vmsof.m v16, v14

  vmsof.m v4, v29, v0.t

  vmsof.m v23, v29

  vmsof.m v20, v31, v0.t

  vmsof.m v7, v28

  vmsof.m v23, v14, v0.t

  vmsof.m v31, v29

  vmsof.m v25, v29, v0.t

  vmsof.m v12, v24

  vmsof.m v8, v30, v0.t

  vmsof.m v1, v6

  vmsof.m v15, v22, v0.t

  vmsof.m v20, v3

  vmsof.m v6, v11, v0.t

  vmsof.m v19, v24

  vmsof.m v20, v19, v0.t

  vmsof.m v1, v17

  vmsof.m v30, v3, v0.t

  vmsof.m v15, v31

  vmsof.m v12, v30, v0.t

  vmsof.m v16, v29

  vmsof.m v7, v3, v0.t

  vmsof.m v15, v6

  vmsof.m v29, v28, v0.t

  vmsof.m v7, v30

  vmsof.m v16, v3, v0.t

  vmsof.m v15, v12

  vmsof.m v14, v10, v0.t

  vmsof.m v23, v30

  vmsof.m v11, v28, v0.t

  vmsof.m v7, v29

  vmsof.m v24, v28, v0.t

  vmsof.m v11, v1

  vmsof.m v6, v30, v0.t

  vmsof.m v7, v17

  vmsof.m v12, v11, v0.t

  vmsof.m v14, v23

  vmsof.m v1, v6, v0.t

  vmsof.m v28, v17

  vmsof.m v14, v23, v0.t

  vmsof.m v6, v28

  vmsof.m v13, v11, v0.t

  vmsof.m v9, v27

  vmsof.m v26, v21, v0.t

  vmsof.m v15, v22

  vmsof.m v24, v26, v0.t

  vmsof.m v7, v17

  vmsof.m v28, v25, v0.t

  vmsof.m v14, v29

  vmsof.m v26, v9, v0.t

  vmsof.m v7, v16

  vmsof.m v8, v14, v0.t

  vmsof.m v22, v11

  vmsof.m v6, v25, v0.t

  vmsof.m v29, v10

  vmsof.m v23, v7, v0.t

  vmsof.m v21, v23

  vmsof.m v15, v29, v0.t

  vmsof.m v28, v29

  vmsof.m v4, v30, v0.t

  vmsof.m v18, v2

  vmsof.m v28, v6, v0.t

  vmsof.m v13, v12

  vmsof.m v18, v4, v0.t

  vmsof.m v11, v15

  vmsof.m v14, v7, v0.t

  vmsof.m v1, v16

  vmsof.m v17, v8, v0.t

  vmsof.m v10, v11

  vmsof.m v4, v16, v0.t

  vmsof.m v13, v26

  vmsof.m v7, v6, v0.t

  vmsof.m v1, v21

  vmsof.m v24, v4, v0.t

  vmsof.m v29, v21

  vmsof.m v7, v14, v0.t

  vmsof.m v13, v1

  vmsof.m v8, v20, v0.t

  vmsof.m v21, v19

  vmsof.m v23, v16, v0.t

  vmsof.m v31, v24

  vmsof.m v17, v27, v0.t

  vmsof.m v23, v6

  vmsof.m v31, v30, v0.t

  vmsof.m v29, v28

  vmsof.m v3, v19, v0.t

  vmsof.m v17, v6

  vmsof.m v12, v18, v0.t

  vmsof.m v31, v26

  vmsof.m v24, v21, v0.t

  vmsof.m v28, v30

  vmsof.m v30, v20, v0.t

  vmsof.m v5, v26

  vmsof.m v4, v10, v0.t

  vmsof.m v30, v10

  vmsof.m v8, v30, v0.t

  vmsof.m v23, v25

  vmsof.m v15, v3, v0.t

  vmsof.m v13, v25

  vmsof.m v29, v11, v0.t

  vmsof.m v31, v9

  vmsof.m v20, v24, v0.t

  vmsof.m v6, v22

  vmsof.m v15, v19, v0.t

  vmsof.m v2, v8

  vmsof.m v11, v21, v0.t

  vmsof.m v29, v27

  vmsof.m v5, v10, v0.t

  vmsof.m v30, v19

  vmsof.m v31, v6, v0.t

  vmsof.m v8, v16

  vmsof.m v21, v4, v0.t

  vmsof.m v22, v29

  vmsof.m v25, v18, v0.t

  vmsof.m v27, v18

  vmsof.m v24, v10, v0.t

  vmsof.m v4, v22

  vmsof.m v26, v6, v0.t

  vmsof.m v25, v23

  vmsof.m v8, v26, v0.t

  vmsof.m v28, v20

  vmsof.m v5, v4, v0.t

  vmsof.m v18, v30

  vmsof.m v19, v29, v0.t

  vmsof.m v29, v16

  vmsof.m v30, v4, v0.t

  vmsof.m v22, v7

  vmsof.m v19, v26, v0.t

  vmsof.m v14, v7

  vmsof.m v27, v4, v0.t

  vmsof.m v3, v6

  vmsof.m v5, v8, v0.t

  vmsof.m v24, v22

  vmsof.m v19, v1, v0.t

  vmsof.m v7, v1

  vmsof.m v4, v23, v0.t

  vmsof.m v25, v29

  vmsof.m v13, v29, v0.t

  vmsof.m v28, v7

  vmsof.m v29, v20, v0.t

  vmsof.m v21, v3

  vmsof.m v26, v24, v0.t

  vmsof.m v17, v21

  vmsof.m v25, v12, v0.t

  vmsof.m v23, v26

  vmsof.m v21, v13, v0.t

  vmsof.m v6, v26

  vmsof.m v14, v18, v0.t

  vmsof.m v23, v6

  vmsof.m v16, v11, v0.t

  vmsof.m v21, v12

  vmsof.m v13, v20, v0.t

  vmsof.m v15, v6

  vmsof.m v22, v3, v0.t

  vmsof.m v5, v22

  vmsof.m v15, v24, v0.t

  vmsof.m v27, v14

  vmsof.m v20, v16, v0.t

  vmsof.m v29, v8

  vmsof.m v21, v2, v0.t

  vmsof.m v12, v17

  vmsof.m v10, v28, v0.t

  vmsof.m v27, v25

  vmsof.m v26, v19, v0.t

  vmsof.m v29, v8

  vmsof.m v5, v13, v0.t

  vmsof.m v1, v8

  vmsof.m v19, v3, v0.t

  vmsof.m v26, v21

  vmsof.m v9, v12, v0.t

  vmsof.m v1, v31

  vmsof.m v29, v1, v0.t

  vmsof.m v21, v14

  vmsof.m v5, v25, v0.t

  vmsof.m v2, v9

  vmsof.m v7, v1, v0.t

  vsetvli t1, t0, e32, m2, ta, ma
  vmsof.m v20, v2

  vmsof.m v4, v18, v0.t

  vmsof.m v6, v30

  vmsof.m v12, v8, v0.t

  vmsof.m v10, v20

  vmsof.m v2, v14, v0.t

  vmsof.m v8, v4

  vmsof.m v20, v4, v0.t

  vmsof.m v26, v16

  vmsof.m v26, v12, v0.t

  vmsof.m v30, v4

  vmsof.m v10, v26, v0.t

  vmsof.m v6, v22

  vmsof.m v20, v6, v0.t

  vmsof.m v22, v30

  vmsof.m v14, v28, v0.t

  vmsof.m v10, v30

  vmsof.m v22, v16, v0.t

  vmsof.m v2, v28

  vmsof.m v8, v26, v0.t

  vmsof.m v26, v28

  vmsof.m v14, v20, v0.t

  vmsof.m v10, v16

  vmsof.m v12, v2, v0.t

  vmsof.m v6, v16

  vmsof.m v18, v6, v0.t

  vmsof.m v8, v20

  vmsof.m v18, v14, v0.t

  vmsof.m v26, v28

  vmsof.m v2, v18, v0.t

  vmsof.m v4, v18

  vmsof.m v16, v30, v0.t

  vmsof.m v8, v18

  vmsof.m v28, v12, v0.t

  vmsof.m v30, v8

  vmsof.m v10, v6, v0.t

  vmsof.m v10, v16

  vmsof.m v6, v30, v0.t

  vmsof.m v10, v22

  vmsof.m v2, v28, v0.t

  vmsof.m v12, v26

  vmsof.m v14, v8, v0.t

  vmsof.m v6, v4

  vmsof.m v14, v24, v0.t

  vmsof.m v20, v24

  vmsof.m v4, v10, v0.t

  vmsof.m v18, v8

  vmsof.m v26, v16, v0.t

  vmsof.m v4, v2

  vmsof.m v8, v12, v0.t

  vmsof.m v20, v4

  vmsof.m v20, v12, v0.t

  vmsof.m v6, v2

  vmsof.m v26, v30, v0.t

  vmsof.m v10, v6

  vmsof.m v16, v24, v0.t

  vmsof.m v18, v26

  vmsof.m v18, v24, v0.t

  vmsof.m v6, v18

  vmsof.m v22, v24, v0.t

  vmsof.m v20, v22

  vmsof.m v2, v14, v0.t

  vmsof.m v4, v30

  vmsof.m v16, v30, v0.t

  vmsof.m v20, v10

  vmsof.m v26, v30, v0.t

  vmsof.m v10, v4

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v6

  vmsof.m v18, v4, v0.t

  vmsof.m v10, v4

  vmsof.m v18, v6, v0.t

  vmsof.m v4, v14

  vmsof.m v26, v2, v0.t

  vmsof.m v18, v20

  vmsof.m v6, v24, v0.t

  vmsof.m v4, v14

  vmsof.m v8, v14, v0.t

  vmsof.m v20, v8

  vmsof.m v4, v2, v0.t

  vmsof.m v26, v24

  vmsof.m v24, v12, v0.t

  vmsof.m v26, v20

  vmsof.m v6, v26, v0.t

  vmsof.m v16, v2

  vmsof.m v26, v16, v0.t

  vmsof.m v28, v8

  vmsof.m v2, v26, v0.t

  vmsof.m v28, v14

  vmsof.m v10, v26, v0.t

  vmsof.m v16, v10

  vmsof.m v14, v22, v0.t

  vmsof.m v2, v22

  vmsof.m v22, v18, v0.t

  vmsof.m v12, v30

  vmsof.m v4, v16, v0.t

  vmsof.m v30, v14

  vmsof.m v4, v24, v0.t

  vmsof.m v10, v20

  vmsof.m v14, v30, v0.t

  vmsof.m v14, v20

  vmsof.m v26, v16, v0.t

  vmsof.m v24, v22

  vmsof.m v20, v18, v0.t

  vmsof.m v22, v26

  vmsof.m v18, v20, v0.t

  vmsof.m v6, v8

  vmsof.m v6, v8, v0.t

  vmsof.m v10, v14

  vmsof.m v22, v16, v0.t

  vmsof.m v6, v12

  vmsof.m v10, v24, v0.t

  vmsof.m v26, v24

  vmsof.m v28, v8, v0.t

  vmsof.m v12, v20

  vmsof.m v4, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v20, v6, v0.t

  vmsof.m v4, v2

  vmsof.m v6, v16, v0.t

  vmsof.m v26, v10

  vmsof.m v14, v22, v0.t

  vmsof.m v20, v16

  vmsof.m v22, v26, v0.t

  vmsof.m v14, v16

  vmsof.m v16, v6, v0.t

  vmsof.m v4, v2

  vmsof.m v12, v22, v0.t

  vmsof.m v14, v8

  vmsof.m v4, v26, v0.t

  vmsof.m v2, v6

  vmsof.m v24, v2, v0.t

  vmsof.m v6, v22

  vmsof.m v8, v22, v0.t

  vmsof.m v10, v20

  vmsof.m v18, v22, v0.t

  vmsof.m v10, v22

  vmsof.m v2, v6, v0.t

  vmsof.m v28, v4

  vmsof.m v4, v8, v0.t

  vmsof.m v2, v14

  vmsof.m v12, v26, v0.t

  vmsof.m v12, v26

  vmsof.m v18, v20, v0.t

  vmsof.m v20, v12

  vmsof.m v2, v8, v0.t

  vmsof.m v2, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v4, v8

  vmsof.m v6, v20, v0.t

  vmsof.m v20, v6

  vmsof.m v6, v10, v0.t

  vmsof.m v26, v4

  vmsof.m v10, v4, v0.t

  vmsof.m v10, v22

  vmsof.m v20, v16, v0.t

  vmsof.m v24, v10

  vmsof.m v10, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v30, v26, v0.t

  vmsof.m v24, v2

  vmsof.m v30, v24, v0.t

  vmsof.m v28, v30

  vmsof.m v20, v8, v0.t

  vmsof.m v18, v22

  vmsof.m v14, v16, v0.t

  vmsof.m v28, v8

  vmsof.m v14, v28, v0.t

  vmsof.m v10, v6

  vmsof.m v2, v22, v0.t

  vmsof.m v2, v4

  vmsof.m v6, v22, v0.t

  vmsof.m v20, v6

  vmsof.m v14, v20, v0.t

  vmsof.m v18, v10

  vmsof.m v18, v22, v0.t

  vmsof.m v12, v10

  vmsof.m v12, v18, v0.t

  vmsof.m v30, v16

  vmsof.m v20, v30, v0.t

  vmsof.m v30, v10

  vmsof.m v4, v18, v0.t

  vmsof.m v24, v14

  vmsof.m v8, v16, v0.t

  vmsof.m v4, v24

  vmsof.m v8, v20, v0.t

  vmsof.m v2, v28

  vmsof.m v12, v20, v0.t

  vmsof.m v4, v26

  vmsof.m v28, v30, v0.t

  vmsof.m v28, v18

  vmsof.m v16, v12, v0.t

  vmsof.m v18, v6

  vmsof.m v6, v2, v0.t

  vmsof.m v14, v28

  vmsof.m v2, v6, v0.t

  vmsof.m v6, v4

  vmsof.m v20, v16, v0.t

  vmsof.m v28, v14

  vmsof.m v30, v18, v0.t

  vsetvli t1, t0, e32, m4, ta, ma
  vmsof.m v20, v4

  vmsof.m v12, v4, v0.t

  vmsof.m v4, v12

  vmsof.m v20, v12, v0.t

  vmsof.m v20, v4

  vmsof.m v16, v8, v0.t

  vmsof.m v20, v4

  vmsof.m v20, v4, v0.t

  vmsof.m v16, v4

  vmsof.m v28, v12, v0.t

  vmsof.m v12, v24

  vmsof.m v8, v28, v0.t

  vmsof.m v4, v12

  vmsof.m v28, v24, v0.t

  vmsof.m v12, v8

  vmsof.m v24, v4, v0.t

  vmsof.m v24, v28

  vmsof.m v4, v8, v0.t

  vmsof.m v24, v4

  vmsof.m v8, v12, v0.t

  vmsof.m v24, v28

  vmsof.m v20, v8, v0.t

  vmsof.m v12, v4

  vmsof.m v16, v4, v0.t

  vmsof.m v20, v16

  vmsof.m v16, v20, v0.t

  vmsof.m v24, v4

  vmsof.m v4, v20, v0.t

  vmsof.m v16, v8

  vmsof.m v28, v12, v0.t

  vmsof.m v24, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v12, v24

  vmsof.m v12, v4, v0.t

  vmsof.m v20, v24

  vmsof.m v24, v20, v0.t

  vmsof.m v16, v28

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v12, v4, v0.t

  vmsof.m v20, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v16, v4

  vmsof.m v16, v8, v0.t

  vmsof.m v28, v12

  vmsof.m v20, v28, v0.t

  vmsof.m v16, v4

  vmsof.m v24, v20, v0.t

  vmsof.m v28, v4

  vmsof.m v4, v12, v0.t

  vmsof.m v12, v4

  vmsof.m v16, v20, v0.t

  vmsof.m v16, v20

  vmsof.m v4, v8, v0.t

  vmsof.m v12, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v12

  vmsof.m v24, v4, v0.t

  vmsof.m v4, v16

  vmsof.m v16, v28, v0.t

  vmsof.m v24, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v12, v24

  vmsof.m v4, v16, v0.t

  vmsof.m v24, v12

  vmsof.m v16, v20, v0.t

  vmsof.m v28, v24

  vmsof.m v4, v20, v0.t

  vmsof.m v12, v8

  vmsof.m v12, v28, v0.t

  vmsof.m v12, v16

  vmsof.m v24, v28, v0.t

  vmsof.m v12, v4

  vmsof.m v4, v28, v0.t

  vmsof.m v16, v28

  vmsof.m v28, v4, v0.t

  vmsof.m v24, v8

  vmsof.m v12, v20, v0.t

  vmsof.m v8, v24

  vmsof.m v4, v16, v0.t

  vmsof.m v24, v12

  vmsof.m v4, v28, v0.t

  vmsof.m v20, v28

  vmsof.m v4, v20, v0.t

  vmsof.m v8, v12

  vmsof.m v20, v24, v0.t

  vmsof.m v20, v28

  vmsof.m v4, v24, v0.t

  vmsof.m v4, v16

  vmsof.m v16, v12, v0.t

  vmsof.m v12, v8

  vmsof.m v20, v28, v0.t

  vmsof.m v16, v12

  vmsof.m v8, v20, v0.t

  vmsof.m v16, v4

  vmsof.m v28, v24, v0.t

  vmsof.m v4, v16

  vmsof.m v16, v12, v0.t

  vmsof.m v24, v20

  vmsof.m v4, v24, v0.t

  vmsof.m v16, v12

  vmsof.m v12, v20, v0.t

  vmsof.m v28, v16

  vmsof.m v4, v20, v0.t

  vmsof.m v24, v12

  vmsof.m v12, v28, v0.t

  vmsof.m v8, v4

  vmsof.m v24, v28, v0.t

  vmsof.m v8, v20

  vmsof.m v28, v16, v0.t

  vmsof.m v20, v4

  vmsof.m v4, v12, v0.t

  vmsof.m v12, v24

  vmsof.m v16, v20, v0.t

  vmsof.m v20, v4

  vmsof.m v28, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v12, v4, v0.t

  vmsof.m v20, v8

  vmsof.m v8, v4, v0.t

  vmsof.m v12, v28

  vmsof.m v8, v28, v0.t

  vmsof.m v4, v24

  vmsof.m v12, v28, v0.t

  vmsof.m v24, v12

  vmsof.m v28, v4, v0.t

  vmsof.m v8, v4

  vmsof.m v12, v20, v0.t

  vmsof.m v4, v28

  vmsof.m v4, v24, v0.t

  vmsof.m v12, v4

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v4

  vmsof.m v8, v12, v0.t

  vmsof.m v12, v16

  vmsof.m v20, v28, v0.t

  vmsof.m v8, v28

  vmsof.m v8, v20, v0.t

  vmsof.m v12, v8

  vmsof.m v16, v20, v0.t

  vmsof.m v12, v20

  vmsof.m v28, v8, v0.t

  vmsof.m v12, v16

  vmsof.m v20, v8, v0.t

  vmsof.m v20, v8

  vmsof.m v20, v16, v0.t

  vmsof.m v20, v8

  vmsof.m v4, v8, v0.t

  vmsof.m v24, v12

  vmsof.m v4, v8, v0.t

  vmsof.m v12, v20

  vmsof.m v12, v20, v0.t

  vmsof.m v8, v12

  vmsof.m v8, v4, v0.t

  vmsof.m v8, v12

  vmsof.m v16, v12, v0.t

  vmsof.m v12, v16

  vmsof.m v28, v12, v0.t

  vmsof.m v12, v16

  vmsof.m v28, v8, v0.t

  vmsof.m v16, v12

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v4

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v28

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v12

  vmsof.m v12, v28, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v20, v0.t

  vmsof.m v16, v12

  vmsof.m v24, v20, v0.t

  vmsof.m v20, v4

  vmsof.m v4, v12, v0.t

  vmsof.m v4, v20

  vmsof.m v20, v28, v0.t

  vmsof.m v4, v8

  vmsof.m v8, v28, v0.t

  vmsof.m v20, v16

  vmsof.m v4, v28, v0.t

  vmsof.m v12, v20

  vmsof.m v12, v8, v0.t

  vmsof.m v24, v28

  vmsof.m v24, v12, v0.t

  vmsof.m v12, v4

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v12

  vmsof.m v8, v20, v0.t

  vmsof.m v4, v28

  vmsof.m v8, v28, v0.t

  vmsof.m v12, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v28, v24

  vmsof.m v8, v4, v0.t

  vmsof.m v4, v24

  vmsof.m v12, v4, v0.t

  vmsof.m v16, v8

  vmsof.m v28, v16, v0.t

  vmsof.m v12, v16

  vmsof.m v8, v4, v0.t

  vsetvli t1, t0, e32, m8, ta, ma
  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vsetvli t1, t0, e64, m1, ta, ma
  vmsof.m v30, v24

  vmsof.m v5, v1, v0.t

  vmsof.m v31, v13

  vmsof.m v8, v21, v0.t

  vmsof.m v7, v2

  vmsof.m v16, v8, v0.t

  vmsof.m v18, v14

  vmsof.m v25, v29, v0.t

  vmsof.m v18, v12

  vmsof.m v10, v29, v0.t

  vmsof.m v25, v17

  vmsof.m v3, v10, v0.t

  vmsof.m v14, v12

  vmsof.m v14, v29, v0.t

  vmsof.m v20, v5

  vmsof.m v11, v3, v0.t

  vmsof.m v6, v31

  vmsof.m v11, v20, v0.t

  vmsof.m v28, v14

  vmsof.m v13, v3, v0.t

  vmsof.m v30, v21

  vmsof.m v7, v4, v0.t

  vmsof.m v23, v24

  vmsof.m v12, v20, v0.t

  vmsof.m v6, v23

  vmsof.m v17, v16, v0.t

  vmsof.m v14, v3

  vmsof.m v14, v2, v0.t

  vmsof.m v9, v25

  vmsof.m v30, v21, v0.t

  vmsof.m v14, v31

  vmsof.m v24, v15, v0.t

  vmsof.m v12, v29

  vmsof.m v30, v23, v0.t

  vmsof.m v12, v7

  vmsof.m v8, v27, v0.t

  vmsof.m v10, v6

  vmsof.m v8, v18, v0.t

  vmsof.m v30, v28

  vmsof.m v31, v18, v0.t

  vmsof.m v20, v2

  vmsof.m v13, v25, v0.t

  vmsof.m v16, v31

  vmsof.m v8, v28, v0.t

  vmsof.m v26, v23

  vmsof.m v23, v29, v0.t

  vmsof.m v12, v30

  vmsof.m v16, v19, v0.t

  vmsof.m v4, v13

  vmsof.m v25, v17, v0.t

  vmsof.m v6, v8

  vmsof.m v7, v16, v0.t

  vmsof.m v26, v29

  vmsof.m v8, v9, v0.t

  vmsof.m v30, v16

  vmsof.m v6, v30, v0.t

  vmsof.m v20, v13

  vmsof.m v26, v7, v0.t

  vmsof.m v29, v9

  vmsof.m v15, v17, v0.t

  vmsof.m v26, v27

  vmsof.m v2, v22, v0.t

  vmsof.m v24, v7

  vmsof.m v9, v24, v0.t

  vmsof.m v19, v12

  vmsof.m v22, v19, v0.t

  vmsof.m v25, v21

  vmsof.m v18, v26, v0.t

  vmsof.m v30, v15

  vmsof.m v31, v12, v0.t

  vmsof.m v25, v22

  vmsof.m v10, v25, v0.t

  vmsof.m v3, v30

  vmsof.m v30, v5, v0.t

  vmsof.m v24, v3

  vmsof.m v27, v31, v0.t

  vmsof.m v21, v1

  vmsof.m v26, v16, v0.t

  vmsof.m v9, v7

  vmsof.m v10, v15, v0.t

  vmsof.m v21, v19

  vmsof.m v19, v18, v0.t

  vmsof.m v24, v8

  vmsof.m v11, v4, v0.t

  vmsof.m v18, v15

  vmsof.m v20, v13, v0.t

  vmsof.m v13, v23

  vmsof.m v3, v11, v0.t

  vmsof.m v4, v5

  vmsof.m v28, v3, v0.t

  vmsof.m v13, v31

  vmsof.m v27, v10, v0.t

  vmsof.m v21, v31

  vmsof.m v28, v29, v0.t

  vmsof.m v9, v28

  vmsof.m v2, v25, v0.t

  vmsof.m v14, v30

  vmsof.m v3, v6, v0.t

  vmsof.m v9, v18

  vmsof.m v8, v6, v0.t

  vmsof.m v24, v25

  vmsof.m v26, v17, v0.t

  vmsof.m v21, v12

  vmsof.m v18, v16, v0.t

  vmsof.m v10, v4

  vmsof.m v4, v2, v0.t

  vmsof.m v22, v31

  vmsof.m v21, v4, v0.t

  vmsof.m v19, v10

  vmsof.m v7, v14, v0.t

  vmsof.m v1, v20

  vmsof.m v19, v27, v0.t

  vmsof.m v31, v24

  vmsof.m v5, v26, v0.t

  vmsof.m v4, v24

  vmsof.m v27, v11, v0.t

  vmsof.m v6, v8

  vmsof.m v23, v20, v0.t

  vmsof.m v30, v31

  vmsof.m v6, v30, v0.t

  vmsof.m v11, v9

  vmsof.m v18, v31, v0.t

  vmsof.m v22, v10

  vmsof.m v21, v8, v0.t

  vmsof.m v23, v4

  vmsof.m v13, v29, v0.t

  vmsof.m v8, v16

  vmsof.m v26, v2, v0.t

  vmsof.m v18, v1

  vmsof.m v11, v20, v0.t

  vmsof.m v15, v4

  vmsof.m v14, v29, v0.t

  vmsof.m v6, v15

  vmsof.m v14, v23, v0.t

  vmsof.m v25, v26

  vmsof.m v2, v21, v0.t

  vmsof.m v7, v18

  vmsof.m v17, v15, v0.t

  vmsof.m v2, v22

  vmsof.m v22, v14, v0.t

  vmsof.m v18, v10

  vmsof.m v11, v20, v0.t

  vmsof.m v7, v14

  vmsof.m v15, v25, v0.t

  vmsof.m v9, v15

  vmsof.m v7, v16, v0.t

  vmsof.m v23, v19

  vmsof.m v30, v1, v0.t

  vmsof.m v6, v27

  vmsof.m v2, v10, v0.t

  vmsof.m v16, v29

  vmsof.m v24, v6, v0.t

  vmsof.m v3, v28

  vmsof.m v2, v16, v0.t

  vmsof.m v30, v4

  vmsof.m v12, v13, v0.t

  vmsof.m v8, v23

  vmsof.m v20, v6, v0.t

  vmsof.m v10, v15

  vmsof.m v23, v4, v0.t

  vmsof.m v5, v10

  vmsof.m v29, v22, v0.t

  vmsof.m v7, v27

  vmsof.m v4, v29, v0.t

  vmsof.m v31, v6

  vmsof.m v24, v1, v0.t

  vmsof.m v27, v20

  vmsof.m v14, v23, v0.t

  vmsof.m v28, v13

  vmsof.m v23, v21, v0.t

  vmsof.m v3, v16

  vmsof.m v29, v27, v0.t

  vmsof.m v10, v13

  vmsof.m v6, v14, v0.t

  vmsof.m v15, v6

  vmsof.m v6, v17, v0.t

  vmsof.m v30, v19

  vmsof.m v17, v12, v0.t

  vmsof.m v29, v27

  vmsof.m v6, v2, v0.t

  vmsof.m v12, v11

  vmsof.m v26, v4, v0.t

  vmsof.m v8, v9

  vmsof.m v23, v15, v0.t

  vmsof.m v2, v14

  vmsof.m v25, v1, v0.t

  vmsof.m v16, v14

  vmsof.m v20, v8, v0.t

  vmsof.m v1, v20

  vmsof.m v10, v31, v0.t

  vmsof.m v21, v25

  vmsof.m v21, v27, v0.t

  vmsof.m v14, v31

  vmsof.m v21, v15, v0.t

  vmsof.m v30, v14

  vmsof.m v20, v27, v0.t

  vmsof.m v15, v8

  vmsof.m v8, v22, v0.t

  vmsof.m v6, v17

  vmsof.m v8, v18, v0.t

  vsetvli t1, t0, e64, m2, ta, ma
  vmsof.m v6, v12

  vmsof.m v26, v24, v0.t

  vmsof.m v18, v2

  vmsof.m v24, v2, v0.t

  vmsof.m v24, v26

  vmsof.m v30, v8, v0.t

  vmsof.m v30, v20

  vmsof.m v4, v14, v0.t

  vmsof.m v12, v6

  vmsof.m v12, v14, v0.t

  vmsof.m v24, v10

  vmsof.m v18, v10, v0.t

  vmsof.m v20, v16

  vmsof.m v14, v20, v0.t

  vmsof.m v8, v20

  vmsof.m v12, v28, v0.t

  vmsof.m v22, v8

  vmsof.m v8, v30, v0.t

  vmsof.m v28, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v26, v2

  vmsof.m v26, v22, v0.t

  vmsof.m v18, v28

  vmsof.m v18, v24, v0.t

  vmsof.m v8, v12

  vmsof.m v10, v30, v0.t

  vmsof.m v10, v22

  vmsof.m v22, v10, v0.t

  vmsof.m v20, v26

  vmsof.m v10, v24, v0.t

  vmsof.m v12, v8

  vmsof.m v2, v14, v0.t

  vmsof.m v14, v12

  vmsof.m v18, v8, v0.t

  vmsof.m v24, v6

  vmsof.m v30, v16, v0.t

  vmsof.m v28, v6

  vmsof.m v18, v6, v0.t

  vmsof.m v2, v6

  vmsof.m v28, v6, v0.t

  vmsof.m v6, v18

  vmsof.m v12, v30, v0.t

  vmsof.m v2, v26

  vmsof.m v22, v28, v0.t

  vmsof.m v2, v12

  vmsof.m v2, v24, v0.t

  vmsof.m v30, v12

  vmsof.m v14, v20, v0.t

  vmsof.m v28, v18

  vmsof.m v18, v12, v0.t

  vmsof.m v6, v28

  vmsof.m v22, v18, v0.t

  vmsof.m v24, v20

  vmsof.m v16, v10, v0.t

  vmsof.m v16, v28

  vmsof.m v8, v6, v0.t

  vmsof.m v30, v24

  vmsof.m v14, v30, v0.t

  vmsof.m v26, v14

  vmsof.m v12, v8, v0.t

  vmsof.m v30, v26

  vmsof.m v22, v12, v0.t

  vmsof.m v26, v4

  vmsof.m v2, v6, v0.t

  vmsof.m v14, v22

  vmsof.m v2, v26, v0.t

  vmsof.m v16, v4

  vmsof.m v12, v26, v0.t

  vmsof.m v6, v2

  vmsof.m v2, v14, v0.t

  vmsof.m v22, v2

  vmsof.m v22, v4, v0.t

  vmsof.m v10, v12

  vmsof.m v16, v10, v0.t

  vmsof.m v26, v4

  vmsof.m v6, v28, v0.t

  vmsof.m v12, v26

  vmsof.m v20, v4, v0.t

  vmsof.m v24, v16

  vmsof.m v6, v22, v0.t

  vmsof.m v12, v16

  vmsof.m v2, v20, v0.t

  vmsof.m v30, v18

  vmsof.m v30, v2, v0.t

  vmsof.m v24, v4

  vmsof.m v16, v30, v0.t

  vmsof.m v20, v22

  vmsof.m v8, v30, v0.t

  vmsof.m v6, v2

  vmsof.m v6, v28, v0.t

  vmsof.m v16, v28

  vmsof.m v20, v22, v0.t

  vmsof.m v28, v10

  vmsof.m v4, v6, v0.t

  vmsof.m v20, v28

  vmsof.m v30, v28, v0.t

  vmsof.m v18, v26

  vmsof.m v10, v2, v0.t

  vmsof.m v8, v16

  vmsof.m v20, v16, v0.t

  vmsof.m v28, v14

  vmsof.m v8, v22, v0.t

  vmsof.m v12, v20

  vmsof.m v26, v20, v0.t

  vmsof.m v28, v24

  vmsof.m v14, v2, v0.t

  vmsof.m v20, v6

  vmsof.m v8, v16, v0.t

  vmsof.m v26, v20

  vmsof.m v10, v30, v0.t

  vmsof.m v8, v14

  vmsof.m v6, v2, v0.t

  vmsof.m v28, v26

  vmsof.m v20, v18, v0.t

  vmsof.m v26, v14

  vmsof.m v20, v30, v0.t

  vmsof.m v12, v2

  vmsof.m v20, v28, v0.t

  vmsof.m v28, v18

  vmsof.m v6, v2, v0.t

  vmsof.m v6, v2

  vmsof.m v12, v22, v0.t

  vmsof.m v18, v2

  vmsof.m v14, v20, v0.t

  vmsof.m v26, v6

  vmsof.m v18, v10, v0.t

  vmsof.m v30, v8

  vmsof.m v24, v20, v0.t

  vmsof.m v10, v6

  vmsof.m v12, v20, v0.t

  vmsof.m v14, v10

  vmsof.m v16, v20, v0.t

  vmsof.m v26, v24

  vmsof.m v20, v30, v0.t

  vmsof.m v22, v2

  vmsof.m v20, v16, v0.t

  vmsof.m v4, v30

  vmsof.m v8, v16, v0.t

  vmsof.m v6, v12

  vmsof.m v22, v2, v0.t

  vmsof.m v24, v22

  vmsof.m v28, v10, v0.t

  vmsof.m v24, v10

  vmsof.m v22, v30, v0.t

  vmsof.m v12, v6

  vmsof.m v8, v6, v0.t

  vmsof.m v26, v12

  vmsof.m v16, v8, v0.t

  vmsof.m v14, v8

  vmsof.m v8, v6, v0.t

  vmsof.m v8, v28

  vmsof.m v14, v6, v0.t

  vmsof.m v2, v18

  vmsof.m v18, v14, v0.t

  vmsof.m v22, v24

  vmsof.m v12, v28, v0.t

  vmsof.m v22, v10

  vmsof.m v8, v24, v0.t

  vmsof.m v30, v6

  vmsof.m v4, v12, v0.t

  vmsof.m v8, v22

  vmsof.m v28, v22, v0.t

  vmsof.m v10, v30

  vmsof.m v18, v28, v0.t

  vmsof.m v24, v4

  vmsof.m v28, v20, v0.t

  vmsof.m v26, v10

  vmsof.m v14, v2, v0.t

  vmsof.m v18, v12

  vmsof.m v20, v2, v0.t

  vmsof.m v26, v28

  vmsof.m v30, v6, v0.t

  vmsof.m v16, v14

  vmsof.m v10, v18, v0.t

  vmsof.m v16, v28

  vmsof.m v26, v30, v0.t

  vmsof.m v2, v28

  vmsof.m v30, v18, v0.t

  vmsof.m v30, v26

  vmsof.m v24, v10, v0.t

  vmsof.m v12, v14

  vmsof.m v4, v30, v0.t

  vmsof.m v16, v30

  vmsof.m v16, v26, v0.t

  vmsof.m v28, v22

  vmsof.m v4, v16, v0.t

  vmsof.m v14, v2

  vmsof.m v6, v4, v0.t

  vmsof.m v26, v22

  vmsof.m v22, v12, v0.t

  vmsof.m v8, v20

  vmsof.m v10, v12, v0.t

  vmsof.m v22, v30

  vmsof.m v16, v12, v0.t

  vmsof.m v30, v18

  vmsof.m v8, v4, v0.t

  vmsof.m v22, v10

  vmsof.m v30, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v22, v20, v0.t

  vsetvli t1, t0, e64, m4, ta, ma
  vmsof.m v8, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v28, v4

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v4

  vmsof.m v24, v20, v0.t

  vmsof.m v16, v4

  vmsof.m v24, v16, v0.t

  vmsof.m v4, v20

  vmsof.m v28, v12, v0.t

  vmsof.m v24, v4

  vmsof.m v16, v8, v0.t

  vmsof.m v28, v8

  vmsof.m v8, v12, v0.t

  vmsof.m v20, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v28, v24

  vmsof.m v8, v28, v0.t

  vmsof.m v28, v20

  vmsof.m v16, v12, v0.t

  vmsof.m v24, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v20, v4

  vmsof.m v16, v24, v0.t

  vmsof.m v4, v8

  vmsof.m v8, v12, v0.t

  vmsof.m v16, v4

  vmsof.m v12, v8, v0.t

  vmsof.m v28, v8

  vmsof.m v20, v16, v0.t

  vmsof.m v8, v20

  vmsof.m v4, v12, v0.t

  vmsof.m v8, v12

  vmsof.m v16, v8, v0.t

  vmsof.m v12, v28

  vmsof.m v24, v8, v0.t

  vmsof.m v28, v16

  vmsof.m v12, v8, v0.t

  vmsof.m v20, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v28, v12

  vmsof.m v24, v12, v0.t

  vmsof.m v24, v8

  vmsof.m v20, v4, v0.t

  vmsof.m v20, v12

  vmsof.m v28, v24, v0.t

  vmsof.m v24, v20

  vmsof.m v24, v8, v0.t

  vmsof.m v12, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v4, v24

  vmsof.m v4, v28, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v12

  vmsof.m v24, v20, v0.t

  vmsof.m v24, v12

  vmsof.m v24, v8, v0.t

  vmsof.m v12, v20

  vmsof.m v8, v4, v0.t

  vmsof.m v8, v24

  vmsof.m v20, v12, v0.t

  vmsof.m v4, v16

  vmsof.m v20, v16, v0.t

  vmsof.m v12, v28

  vmsof.m v20, v4, v0.t

  vmsof.m v24, v8

  vmsof.m v4, v16, v0.t

  vmsof.m v16, v20

  vmsof.m v8, v24, v0.t

  vmsof.m v4, v24

  vmsof.m v24, v12, v0.t

  vmsof.m v28, v20

  vmsof.m v20, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v28, v24

  vmsof.m v8, v28, v0.t

  vmsof.m v20, v12

  vmsof.m v16, v4, v0.t

  vmsof.m v28, v20

  vmsof.m v12, v16, v0.t

  vmsof.m v24, v28

  vmsof.m v8, v4, v0.t

  vmsof.m v20, v28

  vmsof.m v24, v20, v0.t

  vmsof.m v20, v12

  vmsof.m v24, v28, v0.t

  vmsof.m v4, v28

  vmsof.m v4, v28, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v28, v16

  vmsof.m v28, v8, v0.t

  vmsof.m v16, v20

  vmsof.m v28, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v4, v28, v0.t

  vmsof.m v12, v28

  vmsof.m v20, v12, v0.t

  vmsof.m v16, v24

  vmsof.m v4, v20, v0.t

  vmsof.m v28, v8

  vmsof.m v8, v20, v0.t

  vmsof.m v16, v8

  vmsof.m v28, v8, v0.t

  vmsof.m v20, v4

  vmsof.m v20, v28, v0.t

  vmsof.m v20, v24

  vmsof.m v28, v8, v0.t

  vmsof.m v4, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v20, v12

  vmsof.m v4, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v28, v0.t

  vmsof.m v8, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v4, v12

  vmsof.m v8, v12, v0.t

  vmsof.m v4, v24

  vmsof.m v8, v4, v0.t

  vmsof.m v28, v12

  vmsof.m v16, v4, v0.t

  vmsof.m v12, v24

  vmsof.m v16, v28, v0.t

  vmsof.m v4, v12

  vmsof.m v8, v12, v0.t

  vmsof.m v4, v16

  vmsof.m v28, v20, v0.t

  vmsof.m v20, v16

  vmsof.m v4, v16, v0.t

  vmsof.m v8, v28

  vmsof.m v24, v28, v0.t

  vmsof.m v12, v24

  vmsof.m v28, v8, v0.t

  vmsof.m v16, v20

  vmsof.m v12, v28, v0.t

  vmsof.m v16, v28

  vmsof.m v12, v24, v0.t

  vmsof.m v16, v20

  vmsof.m v20, v24, v0.t

  vmsof.m v8, v28

  vmsof.m v28, v12, v0.t

  vmsof.m v24, v16

  vmsof.m v20, v4, v0.t

  vmsof.m v28, v20

  vmsof.m v4, v16, v0.t

  vmsof.m v20, v8

  vmsof.m v16, v20, v0.t

  vmsof.m v4, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v20, v4

  vmsof.m v16, v20, v0.t

  vmsof.m v28, v24

  vmsof.m v28, v24, v0.t

  vmsof.m v24, v20

  vmsof.m v8, v16, v0.t

  vmsof.m v12, v8

  vmsof.m v8, v20, v0.t

  vmsof.m v8, v4

  vmsof.m v20, v16, v0.t

  vmsof.m v12, v20

  vmsof.m v8, v20, v0.t

  vmsof.m v28, v20

  vmsof.m v12, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v20, v24

  vmsof.m v4, v24, v0.t

  vmsof.m v24, v28

  vmsof.m v16, v12, v0.t

  vmsof.m v28, v8

  vmsof.m v28, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v28

  vmsof.m v16, v28, v0.t

  vmsof.m v24, v12

  vmsof.m v12, v28, v0.t

  vmsof.m v28, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v28, v12

  vmsof.m v8, v28, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v4, v0.t

  vmsof.m v16, v12

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v28

  vmsof.m v16, v4, v0.t

  vmsof.m v24, v4

  vmsof.m v28, v16, v0.t

  vmsof.m v16, v28

  vmsof.m v24, v28, v0.t

  vmsof.m v20, v12

  vmsof.m v24, v20, v0.t

  vmsof.m v4, v12

  vmsof.m v12, v24, v0.t

  vmsof.m v8, v20

  vmsof.m v20, v4, v0.t

  vsetvli t1, t0, e64, m8, ta, ma
  vmsof.m v24, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v8, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v24, v16, v0.t

  vmsof.m v16, v24

  vmsof.m v16, v24, v0.t

  vmsof.m v8, v16

  vmsof.m v24, v8, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v24, v16, v0.t

  vmsof.m v8, v24

  vmsof.m v16, v8, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v8, v0.t

  vmsof.m v16, v8

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v16

  vmsof.m v16, v24, v0.t

  vmsof.m v16, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v16, v8

  vmsof.m v16, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v24

  vmsof.m v8, v24, v0.t

  vmsof.m v24, v8

  vmsof.m v16, v8, v0.t

  vmsof.m v8, v16

  vmsof.m v8, v16, v0.t

  vmsof.m v24, v16

  vmsof.m v8, v24, v0.t

  la a0, res
  TEST_CASE(1, t0, 0, ld t0, 0(a0); addi a0, a0, 8)

  TEST_PASSFAIL

RVTEST_CODE_END

  .data
RVTEST_DATA_BEGIN

res:
  .zero 16

RVTEST_DATA_END
